-- VIGÍA Pattern Database Migration
-- Generated: 2026-04-28T06:22:59.704561+00:00
-- Schema: v1.0 | Standard: SANS_FIND_EVIL_2026
-- Source: 110+ forensic cases (synthetic + real datasets)

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

-- Categories
DELETE FROM pattern_categories;
INSERT INTO pattern_categories (category, description, maxims_source, detection_layer) VALUES ('CARNEGIE', 'Patrones de manipulación interpersonal (Dale Carnegie invertido)', 'Dale Carnegie', 'THIRDNESS');
INSERT INTO pattern_categories (category, description, maxims_source, detection_layer) VALUES ('GRICE', 'Violaciones de los máximos cooperativos (Grice invertido)', 'H.P. Grice', 'SECONDNESS');
INSERT INTO pattern_categories (category, description, maxims_source, detection_layer) VALUES ('ECO', 'Rastros semióticos y anacronismos (Umberto Eco)', 'Umberto Eco', 'FIRSTNESS');
INSERT INTO pattern_categories (category, description, maxims_source, detection_layer) VALUES ('PEIRCE', 'Índices físicos y fricciones (Charles Sanders Peirce)', 'C.S. Peirce', 'FIRSTNESS');

-- Patterns
DELETE FROM nlp_patterns;
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('CARNEGIE', 'CARNEGIE_NOBLE_MOTIVE', '(?i)solo quiero ayudar|quiero proteger|por tu seguridad', 0.85, 'Apelación a motivos nobles para ocultar acción hostil', 'VIGIA_CORPUS_v1', 'Caso 049, 091', 'THIRDNESS', 0.255);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('CARNEGIE', 'CARNEGIE_WEAPONIZED_INCOMPETENCE', '(?i)soy un desastre|no sé nada|soy torpe|me confundo|perdón.*rompí', 0.9, 'Fingir incompetencia para evitar auditoría o ganar empatía', 'VIGIA_CORPUS_v1', 'Caso 047, 084', 'THIRDNESS', 0.27);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('CARNEGIE', 'CARNEGIE_PREEMPTIVE_CONFESSION', '(?i)admita sus errores|fue un error|lo siento mucho|soy irresponsable', 0.88, 'Confesión rápida de falta menor para obtener inmunidad sobre falta mayor', 'VIGIA_CORPUS_v1', 'Caso 054, 073, 083', 'THIRDNESS', 0.264);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('CARNEGIE', 'CARNEGIE_FLATTERY_MIRRORING', '(?i)eres (el|la) mejor|gracias por tu ayuda|sin ti no|genial trabajar', 0.8, 'Adulación o espejo lingüístico para bajar defensas', 'VIGIA_CORPUS_v1', 'Caso 013, 102', 'THIRDNESS', 0.24);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('CARNEGIE', 'CARNEGIE_HELPER_TRAP', '(?i)interésese genuinamente|ayudar a ahorrar tiempo|para que no pierdas', 0.87, 'Ofrecer ayuda para insertarse en proceso de decisión o filtrar evidencia', 'VIGIA_CORPUS_v1', 'Caso 076, 087', 'THIRDNESS', 0.261);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('CARNEGIE', 'CARNEGIE_IMPORTANCE_APPEAL', '(?i)haga que la otra persona se sienta importante|se sienta feliz', 0.85, 'Usar jerarquía o superioridad para paralizar al receptor', 'VIGIA_CORPUS_v1', 'Caso 043, 057', 'THIRDNESS', 0.255);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('CARNEGIE', 'CARNEGIE_PRIVACY_SHIELD', '(?i)apelar a los motivos más nobles|protección.*privacidad|seguridad.*compañero', 0.92, 'Usar preocupación por privacidad como vehículo de exfiltración', 'VIGIA_CORPUS_v1', 'Caso 049, 059', 'THIRDNESS', 0.276);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('CARNEGIE', 'CARNEGIE_NORMALIZATION_PRESSURE', '(?i)no es raro|todo el mundo lo sabe|todos lo hacen|es normal', 0.75, 'Usar presión social para anular dudas sobre anomalía', 'VIGIA_CORPUS_v1', 'Caso 009, 011, 012', 'THIRDNESS', 0.22499999999999998);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('CARNEGIE', 'CARNEGIE_ARTIFICIAL_URGENCY', '(?i)urgente|inmediato|ahora mismo|crítico|emergencia', 0.7, 'Crear urgencia falsa para evadir verificación', 'VIGIA_CORPUS_v1', 'Caso 028, 096', 'THIRDNESS', 0.21);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('CARNEGIE', 'CARNEGIE_BORROWED_CREDIBILITY', '(?i)según (estudios|expertos) de \d{4}|investigadores han demostrado', 0.78, 'Citar autoridad inverosímil o no verificable', 'VIGIA_CORPUS_v1', 'Caso 013, 031', 'THIRDNESS', 0.23399999999999999);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('GRICE', 'GRICE_QUANTITY_FLOOD', '(?i)(?i)demasiada información|detalles extremos|500 páginas|200 PDFs|volumen.*datos', 0.85, 'Violación del máximo de cantidad: saturar con información irrelevante', 'VIGIA_CORPUS_v1', 'Caso 045, 057, 092, 094', 'SECONDNESS', 0.255);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('GRICE', 'GRICE_QUANTITY_STARVATION', '(?i)información incompleta|falta.*contexto|no incluyas.*texto|brevedad excesiva', 0.8, 'Violación del máximo de cantidad: omisión de información crítica', 'VIGIA_CORPUS_v1', 'Caso 051, 106', 'SECONDNESS', 0.24);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('GRICE', 'GRICE_QUALITY_UNVERIFIABLE', '(?i)según estudios de \d{4}|expertos dicen|sin fuente|no verificable', 0.82, 'Violación del máximo de calidad: afirmación sin evidencia', 'VIGIA_CORPUS_v1', 'Caso 013, 031', 'SECONDNESS', 0.24599999999999997);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('GRICE', 'GRICE_QUALITY_FALSE_NORMALITY', '(?i)mantenimiento\. todo bien\.|todo ok|sin novedad|no hay problema', 0.88, 'Violación del máximo de calidad: normalización sin sustento', 'VIGIA_CORPUS_v1', 'Caso 051, 060', 'SECONDNESS', 0.264);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('GRICE', 'GRICE_RELATION_IRRELEVANCE', '(?i)no relacionado con|irrelevante para|fuera de contexto|no aplica', 0.75, 'Violación del máximo de relación: información desconectada del problema', 'VIGIA_CORPUS_v1', 'Caso 044, 088', 'SECONDNESS', 0.22499999999999998);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('GRICE', 'GRICE_MANNER_CHAOS', '(?i)caos informativo|confusión masiva|pánico colectivo|saturación', 0.9, 'Violación del máximo de manera: caos deliberado para ocultar', 'VIGIA_CORPUS_v1', 'Caso 050, 112', 'SECONDNESS', 0.27);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('GRICE', 'GRICE_MANNER_AMBIGUITY', '(?i)lenguaje ambiguo|explicación confusa|no está claro|múltiples interpretaciones', 0.78, 'Violación del máximo de manera: opacidad intencional', 'VIGIA_CORPUS_v1', 'Caso 030, 108', 'SECONDNESS', 0.23399999999999999);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('GRICE', 'GRICE_DEFENSIVE_EVASION', '(?i)no puedo hablar|no puedo seguir|es sensible|bajo presión', 0.85, 'Violación combinada: cantidad + calidad + relación por evasión', 'VIGIA_CORPUS_v1', 'Caso 014, 016', 'SECONDNESS', 0.255);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('GRICE', 'GRICE_DESTRUCTION_REQUEST', '(?i)por favor no.*incluyas|borrá.*original|no menciones.*nadie', 0.95, 'Solicitud explícita de destruir evidencia de comunicación', 'VIGIA_CORPUS_v1', 'Caso 006 (M57-Jean)', 'SECONDNESS', 0.285);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('GRICE', 'GRICE_EVIDENCE_CLEANING', '(?i)limpieza de logs|borrado de rastros|eliminación de evidencia|no ensuciar', 0.92, 'Justificación de destrucción de evidencia como ''limpieza''', 'VIGIA_CORPUS_v1', 'Caso 073, 087', 'SECONDNESS', 0.276);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('ECO', 'ECO_KEYBOARD_SLIP_CYRILLIC', '(?i)ghbdtn|vjcrdf|ckfdf|ыгвщ|кщще|cnfnbz|cnhfyt|д -дф', 0.95, 'Desliz de teclado: texto cirílico tipeado con layout latino', 'VIGIA_CORPUS_v1', 'Caso 046, 056, 086, 104', 'FIRSTNESS', 0.285);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('ECO', 'ECO_SLAVIC_SYNTAX', '(?i)make (function|restart|delete) (for|of)|missing articles|no article', 0.9, 'Sintaxis eslava en inglés: omisión de artículos, uso atípico de ''make''', 'VIGIA_CORPUS_v1', 'Caso 006 (NIST), 081', 'FIRSTNESS', 0.27);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('ECO', 'ECO_ANACHRONISM_TOOL', '(?i)Windows 7.*Windows 11|Windows XP.*2026|herramienta vieja.*sistema nuevo', 0.88, 'Herramienta incompatible con entorno temporal del sistema', 'VIGIA_CORPUS_v1', 'Caso 044, 090, 107', 'FIRSTNESS', 0.264);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('ECO', 'ECO_SYNTHETIC_JITTER', '(?i)jitter.*uniform|intervalos.*exactos|varianza.*nula|entropía.*nula', 0.92, 'Aleatoriedad demasiado perfecta: ley de máquina simulando humano', 'VIGIA_CORPUS_v1', 'Caso 061, 089, 105', 'FIRSTNESS', 0.276);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('ECO', 'ECO_FALSE_AMATEUR_TRAIL', '(?i)PLAN_DE_ATAQUE|herramientas viejas.*mal configuradas|script-kiddie', 0.93, 'Rastro obvio de ''aficionado'' para ocultar operación sofisticada', 'VIGIA_CORPUS_v1', 'Caso 052, 079, 090, 111', 'FIRSTNESS', 0.279);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('ECO', 'ECO_HOMOGLYPH_WATERMARK', '(?i)homóglifo|cirílico.*posición|о.*en lugar de o|fábrica de consistencia', 0.96, 'Marca de agua oculta mediante caracteres homóglifos en posición fija', 'VIGIA_CORPUS_v1', 'Caso 055', 'FIRSTNESS', 0.288);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('ECO', 'ECO_PLATFORM_CONTAMINATION', '(?i)ipconfig.*linux|route print.*bash|ifconfig.*Windows 11', 0.91, 'Comando de un SO ejecutado en otro: contaminación de memoria muscular', 'VIGIA_CORPUS_v1', 'Caso 075, 098', 'FIRSTNESS', 0.273);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('ECO', 'ECO_INHUMAN_PERFECTION', '(?i)perfección.*no humana|demasiado limpio|cero errores|sin reintentos', 0.89, 'Proceso sin entropía humana: automatización disfrazada de operador', 'VIGIA_CORPUS_v1', 'Caso 100', 'FIRSTNESS', 0.267);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('ECO', 'ECO_SYNTHETIC_IDENTITY', '(?i)deepfake.*voz|síntesis.*voz|armónicos.*perfectos|voz.*sintética', 0.94, 'Identidad simulada mediante síntesis de voz o estilo algorítmico', 'VIGIA_CORPUS_v1', 'Caso 080, 093', 'FIRSTNESS', 0.282);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('ECO', 'ECO_SEMIOTIC_COLLISION', '(?i)colisión semiótica|contra-veredicto|formato canónico.*inyectado', 0.99, 'Ataque dirigido contra el propio sistema de inferencia (meta-ataque)', 'VIGIA_CORPUS_v1', 'Caso 110', 'FIRSTNESS', 0.297);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('ECO', 'ECO_TABOO_EXPLOITATION', '(?i)muerte|fallecimiento|condolencias|luto|funeral', 0.97, 'Uso de tabú social para anular protocolo de desconfianza', 'VIGIA_CORPUS_v1', 'Caso 099', 'FIRSTNESS', 0.291);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('ECO', 'ECO_PLAUSIBLE_DENIABILITY', '(?i)gato.*teclado|perro.*mouse|accidental.*tocó|se resbaló.*mouse', 0.85, 'Explicación pueril para error que requiere intención', 'VIGIA_CORPUS_v1', 'Caso 056, 014', 'FIRSTNESS', 0.255);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('PEIRCE', 'PEIRCE_TIMESTOMP_FRICTION', '(?i)ctime.*mtime|timestomp|fecha.*modificación.*diferente', 0.9, 'Inconsistencia temporal en metadatos', 'VIGIA_CORPUS_v1', 'Caso 024', 'FIRSTNESS', 0.27);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('PEIRCE', 'PEIRCE_ENTROPY_INVERSION', '(?i)entropy.*0\.000|padding.*zeros|archivo.*50MB.*ceros', 0.88, 'Entropía anómala indicanti manipulación', 'VIGIA_CORPUS_v1', 'Caso 025', 'FIRSTNESS', 0.264);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('PEIRCE', 'PEIRCE_PROCESS_MASQUERADE', '(?i)process.*hollowing|svchost.*no.*system32|doppelgänger', 0.92, 'Proceso legítimo en ubicación ilegítima', 'VIGIA_CORPUS_v1', 'Caso 026, 020', 'FIRSTNESS', 0.276);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('PEIRCE', 'PEIRCE_MISSING_INDEX', '(?i)bash_history.*sudo.*sin.*log|comando.*no.*registrado', 0.85, 'Ausencia de rastro donde debería existir', 'VIGIA_CORPUS_v1', 'Caso 009', 'FIRSTNESS', 0.255);
INSERT INTO nlp_patterns (category, pattern_name, pattern_regex, weight, description, source, case_origin, peirce_layer, confidence_boost) VALUES ('PEIRCE', 'PEIRCE_CIRCADIAN_BREAK', '(?i)login.*3am.*circadian|keystroke.*35%.*más|rítmo.*nocturno', 0.91, 'Ruptura de ritmo circadiano humano', 'VIGIA_CORPUS_v1', 'Caso 048, 007', 'FIRSTNESS', 0.273);

COMMIT;
PRAGMA foreign_keys=ON;