"""Bilingual string tables for the audience reports.

Rules
-----
* ``STRINGS["en"]`` and ``STRINGS["es"]`` carry exactly the same keys. A test
  asserts parity; ``t()`` raises ``KeyError`` on a missing key instead of
  falling back to the other language (a silent fallback is how a half
  translated report ships unnoticed).
* Sealed vocabulary is never translated. Verdict values, schema names and
  bundle field names appear inside these strings only as the literal token the
  bundle uses (``MALICE``, ``agent_verdict``), in both tables.
* No emoji, no generation timestamps, no formulas. Prose in the ``es`` table is
  neutral Rioplatense Spanish.
* Multi-line values are Markdown fragments; renderers join them with blank
  lines. ``{placeholders}`` are filled with ``str.format`` by ``t()``.
"""

from __future__ import annotations

from typing import Any

_EN: dict[str, str] = {
    # ------------------------------------------------------------------ common
    "doc.title_junior": "VIGÍA verdict, explained for a SOC analyst",
    "doc.title_expert": "VIGÍA sealed verdict, expert review sheet",
    "header.case": "Case",
    "header.schema": "Bundle family",
    "header.source": "Source bundle",
    "header.source_sha256": "Source SHA-256",
    "header.report_version": "Report layout version",
    "header.audience": "Audience",
    "header.col_value": "Value",
    "audience.junior": "junior SOC analyst",
    "audience.expert": "expert forensic examiner",
    "header.disclaimer": (
        "This document carries NO verdict authority. It presents a sealed result "
        "verbatim; it computed nothing, reconciled nothing and can be regenerated "
        "from the bundle bytes at any time. If this text and the bundle ever "
        "disagree, the bundle is right and this file is stale."
    ),
    "header.verbatim_note": (
        "Values quoted from the bundle appear exactly as sealed, including their "
        "original language, spelling and numeric form. That is the evidence, not a "
        "rendering defect."
    ),
    "gap.absent": "not present in this bundle",
    "gap.family_absent": "this bundle family does not record this field",
    "gap.hash_note": (
        "Hashes are only comparable within one bundle family. An EBS v1 "
        "`bundle_hash`, an agent bundle's sidecar digest and a Mode 2 "
        "`bundle_sha256` are computed over different payloads (KNOWN_LIMITATIONS "
        "L-030, L-031)."
    ),
    "footer.note": (
        "Generated by `vigia.report` {version} from the bundle whose SHA-256 is "
        "`{sha256}`. No timestamp is recorded on purpose: the same bundle bytes "
        "must always produce the same report bytes."
    ),
    "section.gaps": "Gaps and limitations",
    "section.glossary": "Glossary of sealed terms used above",
    "section.verify": "How to verify this bundle yourself",
    "glossary.intro": (
        "Terms below are the literal tokens the bundle uses. They are explained, "
        "never translated."
    ),
    "verify.intro": (
        "Every check below is independent of this document. Run it on the bundle "
        "file, not on this report."
    ),
    "verify.ebs": (
        "EBS v1 bundle: `python3 forensics/verify_ebs_v1.py {name}` recomputes "
        "`bundle_hash` and `analysis_fingerprint` over the payload (everything "
        "except `integrity`). Exit 0 means every check passed; exit 1 lists the "
        "failing checks."
    ),
    "verify.agent": (
        "Agent bundle: `sha256sum -c {name}.sha256` checks the file against the "
        "digest written next to it when it was sealed. If a `_reasoning_trace.json` "
        "sibling exists, `vigia.core.reasoning_trace.verify_reasoning_trace` binds "
        "its verdict to `agent_verdict`."
    ),
    "verify.mcp": (
        "Mode 2 investigation bundle: `python3 verify_tool_log.py {name}` walks the "
        "`tool_execution_log` hash chain (v1 and v2, plus the `chain_tip_sha256` "
        "anchor when present). Exit 0 chain intact, 1 chain broken, 2 usage error. "
        "Pass `--hmac-key-file` for keyed verification."
    ),
    "verify.family_note": (
        "Running a verifier on the wrong family reports non-compliance by design "
        "(docs/EXECUTION_MODES.md). Use the command that matches the family named "
        "in the header."
    ),
    "verify.unknown": (
        "The family could not be identified, so no verifier applies. Compare the "
        "SHA-256 in the header against your own `sha256sum` of the file."
    ),
    "schema.ebs_v1": (
        "EBS v1: the sealed pipeline bundle (`evidence_graph`, `decision_trace`, "
        "`integrity`). Produced by `vigia/core/bundle_builder.py`."
    ),
    "schema.agent_audit": (
        "Agent audit bundle: output of `python3 vigia_agent.py` (Mode 1). Carries "
        "`agent_verdict`, `audit_trail`, `pipeline_results` and a deterministic "
        "`narrative`. Numbers are exact Fractions."
    ),
    "schema.mcp_investigation": (
        "Mode 2 investigation bundle: findings and a tamper-evident "
        "`tool_execution_log` written during a Claude Code / MCP investigation. "
        "Field names vary between cases."
    ),
    "schema.unknown": (
        "Unrecognized document: none of the three bundle families matched. "
        "Nothing is inferred from it."
    ),
    "unknown.body": (
        "The file did not match any known bundle family, so there is no verdict to "
        "present. Only the source hash above is reported. Open the JSON directly or "
        "ask the examiner which tool produced it."
    ),

    # ------------------------------------------------------------ junior view
    "junior.s1.title": "1. The verdict",
    "junior.s1.intro": (
        "This is the sealed result, copied character by character from the bundle. "
        "Each line names the field it came from."
    ),
    "junior.s1.none": (
        "The bundle carries no verdict-bearing field. Treat the case as unresolved "
        "and check the gaps section."
    ),
    "junior.s1.disagreement": (
        "Two verdict-bearing fields disagree. This report does not pick one; the "
        "bundle sealed both and an examiner has to explain the difference. Do not "
        "act on the more severe one just because it is more severe."
    ),
    "junior.s1.hypothesis_note": (
        "`best_hypothesis` is the label of the winning abductive hypothesis, not a "
        "verdict. The verdict is `agent_verdict`."
    ),
    "junior.s2.title": "2. What this verdict means",
    "junior.s2.scale_intro": (
        "VIGÍA uses a five-rung scale. The rung says how much deliberate behavior "
        "the evidence supports; it does not say who did it or whether a law was "
        "broken."
    ),
    "junior.s2.col_verdict": "Verdict",
    "junior.s2.col_meaning": "Meaning",
    "junior.s2.col_bar": "Evidence bar",
    "junior.s2.this_one": "This bundle",
    "junior.s2.mode1_note": (
        "Mode 1 (`vigia_agent.py`) has no INTENT rung: borderline cases that would "
        "qualify as INTENT are capped at SUSPICION by the scoring pipeline "
        "(CLAUDE.md, Verdict Scale). An agent bundle reading SUSPICION can therefore "
        "be stronger than it looks; read the narrative."
    ),
    "scale.NOISE.meaning": (
        "Everything observed is explained by misconfiguration, software error or "
        "normal operations."
    ),
    "scale.NOISE.bar": "Single source is enough.",
    "scale.SUSPICION.meaning": (
        "A structural anomaly exists, but there is no evidence of deliberate "
        "concealment or coordination."
    ),
    "scale.SUSPICION.bar": "Single source plus a documented deviation from baseline.",
    "scale.INTENT.meaning": (
        "Deliberate decisions were made to produce this outcome."
    ),
    "scale.INTENT.bar": "Two independent sources and a passed refutation protocol.",
    "scale.MALICE.meaning": (
        "Active concealment of intent: the actor is hiding that they are hiding "
        "(log deletion, timestamp tampering, masquerading, false flags)."
    ),
    "scale.MALICE.bar": (
        "Two independent sources, refutation protocol, and a populated "
        "`devil_advocate`."
    ),
    "scale.ABSTAIN.meaning": (
        "Not enough evidence to classify. The gap is documented as a limitation."
    ),
    "scale.ABSTAIN.bar": "Explicit statement of what is missing.",
    "scale.ERROR.meaning": (
        "The run did not complete. This is an exit-code label, not a forensic "
        "finding."
    ),
    "scale.ERROR.bar": "Not applicable.",
    "junior.s3.title": "3. What to do next",
    "junior.s3.intro": (
        "Generic SOC steps for this rung. They are not case-specific advice and "
        "they do not come from the bundle; adapt them to your runbook."
    ),
    "next.NOISE": (
        "- Close or de-prioritize the alert, keeping the bundle with the ticket.\n"
        "- Note what normal behavior explained the anomaly, so the next analyst "
        "does not re-open it.\n"
        "- If the source system is critical, schedule a routine review rather than "
        "an incident."
    ),
    "next.SUSPICION": (
        "- Keep the case open. Do not contain or block yet.\n"
        "- Look for a second, independent source for the same anomaly (another "
        "host, another log, another sensor).\n"
        "- Ask an experienced analyst to review before escalating."
    ),
    "next.INTENT": (
        "- Escalate to incident response. Deliberate behavior is established.\n"
        "- Preserve the original evidence read-only; work only on copies.\n"
        "- Start scoping: which other systems could the same actor have touched?"
    ),
    "next.MALICE": (
        "- Escalate now. Concealment means the actor expects to be looked for.\n"
        "- Preserve everything, including logs the actor may have tried to "
        "delete.\n"
        "- Containment decisions belong to incident response and management, not "
        "to this report."
    ),
    "next.ABSTAIN": (
        "- Do not treat this as benign. It means undecided.\n"
        "- Read the gaps section: it lists what evidence would resolve the case.\n"
        "- Collect that evidence, re-run the analysis, and compare the two "
        "bundles."
    ),
    "next.ERROR": (
        "- The analysis did not finish. Fix the run before reasoning about the "
        "case.\n"
        "- Check the audit trail or log for the failing step."
    ),
    "next.UNKNOWN": (
        "- The verdict token is not on the standard scale. Ask the examiner what "
        "produced it before acting."
    ),
    "junior.s4.title": "4. What NOT to conclude",
    "notnot.NOISE": (
        "NOISE is not proof of innocence. It means the analyzed artifacts are "
        "explained without intent; artifacts that were never collected are not "
        "covered."
    ),
    "notnot.SUSPICION": (
        "SUSPICION is not attribution. Nothing here says who did it, and the "
        "anomaly may still have an innocent cause that was not tested."
    ),
    "notnot.INTENT": (
        "INTENT is not guilt. It is an inference about deliberate behavior in the "
        "analyzed artifacts, reached through a refutation protocol, not a legal "
        "finding."
    ),
    "notnot.MALICE": (
        "MALICE describes a concealment pattern in the analyzed artifacts. It is "
        "not a legal finding, not an identification of a person, and not a "
        "statement about damage."
    ),
    "notnot.ABSTAIN": (
        "ABSTAIN is not benign and not malicious. It is the system refusing to "
        "guess."
    ),
    "notnot.ERROR": "An ERROR run says nothing about the evidence.",
    "notnot.generic": (
        "No presentation, this one included, can add evidence that the bundle does "
        "not contain."
    ),
    "junior.s5.title": "5. Findings, in plain language",
    "junior.s5.intro_mcp": (
        "Each finding below was recorded by the investigator during a Mode 2 "
        "session. Its verdict, confidence and status are quoted verbatim, followed "
        "by the three Peircean layers it was reasoned through."
    ),
    "junior.s5.intro_agent": (
        "Agent bundles do not carry per-finding verdicts. They record signals "
        "(one per analyzed artifact) and one abductive hypothesis. The sealed "
        "narrative below is the pipeline's own account."
    ),
    "junior.s5.intro_ebs": (
        "EBS v1 bundles record a decision trace and, when the CAIE module ran, a "
        "reason string. Both are quoted verbatim."
    ),
    "junior.s5.no_findings": "No findings or signals are recorded in this bundle.",
    "junior.s5.no_signal_verdict": (
        "Signals carry no verdict of their own; only the case does."
    ),
    "junior.s5.peirce_first": (
        "Firstness: what was observed, described without interpretation."
    ),
    "junior.s5.peirce_second": (
        "Secondness: how the observation clashes with what normal looks like."
    ),
    "junior.s5.peirce_third": (
        "Thirdness: what repeatable, deliberate pattern would produce it."
    ),
    "junior.s5.narrative_label": "Sealed narrative (verbatim)",
    "junior.s5.gates_title": "Corrections recorded before the verdict was sealed",
    "junior.s5.gates_intro": (
        "A candidate verdict that a gate rejected never became the verdict. This is "
        "the system correcting itself before emission, not a contradiction."
    ),
    "junior.s5.summary_label": "Investigator's executive summary (verbatim)",
    "signals.col_artifact": "Artifact",
    "signals.col_type": "Evidence type",
    "signals.col_source": "Source tool",
    "signals.col_confidence": "Confidence",
    "signals.col_z": "z-score",
    "signals.exact_note": (
        "Confidence and z-score are exact fractions, shown as numerator/denominator. "
        "They are not percentages."
    ),
    "finding.verdict": "Verdict",
    "finding.confidence": "Confidence",
    "finding.status": "Status",
    "finding.artifacts": "Artifacts",
    "finding.tools": "Tools used",
    "finding.carnegie": "Persuasion pattern (Carnegie)",
    "finding.devil_advocate": "Strongest benign explanation (`devil_advocate`)",
    "finding.corroboration": "Corroboration",
    "finding.untitled": "(untitled finding)",
    "junior.s6.title": "6. MITRE ATT&CK techniques mentioned",
    "junior.s6.intro": (
        "Technique ids found in the bundle, with MITRE's own name and description "
        "where VIGÍA's local dictionary has them. Descriptions are MITRE's English "
        "text and are not translated."
    ),
    "junior.s6.none": "No MITRE technique id is recorded in this bundle.",
    "mitre.col_id": "Technique",
    "mitre.col_name": "Name",
    "mitre.col_where": "Found in",
    "mitre.not_local": (
        "not in VIGÍA's local dictionary; URL derived from the id"
    ),
    "junior.s7.title": "7. Where this sits in the SANS incident lifecycle",
    "junior.s7.intro": (
        "A sealed verdict is an output of the Identification phase. Containment, "
        "eradication and recovery are human decisions that this report does not "
        "make."
    ),
    "junior.s7.phase_in_bundle": "Phase recorded in the bundle (`sans_phase`)",
    "junior.s7.sans_compliance_note": (
        "`sans_compliance` in an agent bundle lists hackathon submission criteria "
        "(audit trail present, self-correction ran, and so on). It is not a PICERL "
        "phase."
    ),
    "picerl.col_phase": "Phase",
    "picerl.col_desc": "What happens here",
    "picerl.preparation": "Build and maintain response capability: policy, tooling, training.",
    "picerl.identification": (
        "Detect, alert and decide whether the event is an incident. Initial "
        "evidence collection and triage. VIGÍA's verdict lives here."
    ),
    "picerl.containment": (
        "Limit damage: isolate compromised systems while preserving evidence."
    ),
    "picerl.eradication": "Remove the malicious artifact and its root cause.",
    "picerl.recovery": "Restore normal operation and monitor closely.",
    "picerl.lessons_learned": (
        "Document the incident, improve detections and playbooks."
    ),
    "junior.s8.intro": (
        "Anything the bundle does not say is listed here rather than filled in. "
        "Missing does not mean absent from reality; it means not recorded."
    ),
    "junior.s8.none": "The bundle reader reported no gaps.",
    "junior.s8.bundle_limitations": "Limitations the bundle itself declares",
    "junior.s8.reader_gaps": "Fields the bundle reader could not find",

    # ------------------------------------------------------------ expert view
    "expert.s1.title": "1. Chain of custody",
    "expert.s1.intro": (
        "Every custody anchor this family defines, present or explicitly absent. "
        "Values are the sealed literals."
    ),
    "expert.s1.sidecar_note": (
        "Agent bundles do not embed their own digest (self-reference). The digest "
        "of the file lives in the `.sha256` sidecar and in `audit_trail`."
    ),
    "custody.col_field": "Field",
    "custody.col_value": "Sealed value",
    "expert.s2.title": "2. Verdict-bearing fields",
    "expert.s2.col_source": "Field",
    "expert.s2.col_verdict": "Value",
    "expert.s2.col_confidence": "Confidence",
    "expert.s2.col_pointer": "JSON pointer",
    "expert.s2.disagreement": (
        "`verdict_disagreement` is set: the fields above do not agree. The bundle "
        "sealed both; nothing here reconciles them (see "
        "docs/VIGIA_TECHNICAL_STATE_EN.md, section 12.3)."
    ),
    "expert.s2.none": "No verdict-bearing field found.",
    "expert.s3.title": "3. Peircean triad per finding (verbatim)",
    "expert.s3.none_agent": (
        "Agent bundles carry no per-signal triad. The abductive narrative is the "
        "only Peircean text sealed in this family."
    ),
    "expert.s3.none": "No Peircean triad is recorded in this bundle.",
    "expert.s3.layer_first": "Firstness",
    "expert.s3.layer_second": "Secondness",
    "expert.s3.layer_third": "Thirdness",
    "expert.s4.title": "4. Exact sealed scores",
    "expert.s4.intro": (
        "Each value is the literal sealed in the bundle: serialized Fractions as "
        "`numerator/denominator`, floats as their JSON literal. Nothing is rounded "
        "or converted. A float in a sealed path is itself a finding (KNOWN_LIMITATIONS "
        "L-021, L-073)."
    ),
    "expert.s4.col_pointer": "JSON pointer",
    "expert.s4.col_value": "Sealed literal",
    "expert.s4.none": "No numeric score is sealed in this bundle.",
    "expert.s5.title": "5. Daubert gates, refutation and devil's advocate",
    "expert.s5.intro": (
        "Records of a gate, downgrade or self-correction, as stored. These are the "
        "pre-emission corrections that make a verdict defensible."
    ),
    "expert.s5.gates_none": "No gate or self-correction record is present.",
    "expert.s5.da_title": "`devil_advocate` entries",
    "expert.s5.da_none": "No `devil_advocate` field is present.",
    "expert.s5.da_missing_for_intent": (
        "GAP: a verdict of {verdict} is sealed but no `devil_advocate` is present. "
        "The Refutation Protocol (CLAUDE.md, Step 3) requires one for INTENT and "
        "MALICE. This report does not alter the verdict; it records the gap "
        "(KNOWN_LIMITATIONS L-022)."
    ),
    "expert.s5.col_pointer": "JSON pointer",
    "expert.s5.col_value": "Sealed value",
    "expert.s6.title": "6. Execution record",
    "expert.s6.kind": "Record type",
    "expert.s6.entries": "Entries",
    "expert.s6.chain_version": "`chain_version`",
    "expert.s6.chain_tip": "`chain_tip_sha256`",
    "expert.s6.chain_tip_hmac": "`chain_tip_hmac`",
    "expert.s6.present": "present",
    "expert.s6.absent": "absent",
    "expert.s6.sha256_entries": "Entries carrying `entry_sha256`",
    "expert.s6.start": "`start_time`",
    "expert.s6.end": "`end_time`",
    "expert.s6.histogram": "Histogram (sorted by count, then name)",
    "expert.s6.listing": "First {cap} entries",
    "expert.s6.truncated": (
        "Listing truncated at {cap} of {total} entries. Open the bundle for the rest."
    ),
    "expert.s6.system_state": "`system_state` fields",
    "expert.s6.none": "This bundle carries no execution record.",
    "expert.s6.col_label": "Label",
    "expert.s6.col_count": "Count",
    "expert.s8.title": "8. Known limitations",
    "expert.s8.intro": (
        "Limitations declared by the bundle, gaps found by the reader, and the "
        "repository limitations that bound any presentation of this family."
    ),
    "expert.s8.pointers": (
        "- L-004: narrative and prompt content are examiner-authored input, not "
        "evidence.\n"
        "- L-020: Mode 2 bundles carry no granular `audit_trail`.\n"
        "- L-022: `devil_advocate` validation is partly architectural.\n"
        "- L-030 / L-031: sealing paths differ; hashes are not comparable across "
        "families and `verify_ebs_v1.py` rejects non-EBS bundles by design.\n"
        "- L-056: Mode 1 and Mode 2 alert architectures diverge.\n"
        "- L-074: this presentation renders sealed fields verbatim and cannot fill "
        "gaps a family does not record."
    ),
}

_ES: dict[str, str] = {
    # ------------------------------------------------------------------ común
    "doc.title_junior": "Veredicto VIGÍA, explicado para un analista SOC",
    "doc.title_expert": "Veredicto sellado VIGÍA, hoja de revisión experta",
    "header.case": "Caso",
    "header.schema": "Familia de bundle",
    "header.source": "Bundle de origen",
    "header.source_sha256": "SHA-256 de origen",
    "header.report_version": "Versión del formato de reporte",
    "header.audience": "Audiencia",
    "header.col_value": "Valor",
    "audience.junior": "analista SOC junior",
    "audience.expert": "perito forense experto",
    "header.disclaimer": (
        "Este documento NO tiene autoridad de veredicto. Presenta un resultado "
        "sellado tal cual; no calculó nada, no reconcilió nada y puede regenerarse "
        "desde los bytes del bundle en cualquier momento. Si este texto y el bundle "
        "alguna vez difieren, el bundle tiene razón y este archivo quedó viejo."
    ),
    "header.verbatim_note": (
        "Los valores citados del bundle aparecen exactamente como fueron sellados, "
        "con su idioma, ortografía y forma numérica originales. Eso es la evidencia, "
        "no un defecto de presentación."
    ),
    "gap.absent": "no presente en este bundle",
    "gap.family_absent": "esta familia de bundle no registra este campo",
    "gap.hash_note": (
        "Los hashes sólo son comparables dentro de una misma familia de bundle. El "
        "`bundle_hash` de EBS v1, el digest del sidecar de un bundle de agente y el "
        "`bundle_sha256` de Modo 2 se calculan sobre payloads distintos "
        "(KNOWN_LIMITATIONS L-030, L-031)."
    ),
    "footer.note": (
        "Generado por `vigia.report` {version} a partir del bundle cuyo SHA-256 es "
        "`{sha256}`. No se registra fecha a propósito: los mismos bytes de bundle "
        "tienen que producir siempre los mismos bytes de reporte."
    ),
    "section.gaps": "Huecos y limitaciones",
    "section.glossary": "Glosario de términos sellados usados arriba",
    "section.verify": "Cómo verificar este bundle por tu cuenta",
    "glossary.intro": (
        "Los términos de abajo son los tokens literales que usa el bundle. Se "
        "explican, nunca se traducen."
    ),
    "verify.intro": (
        "Cada chequeo de abajo es independiente de este documento. Corrélo sobre el "
        "archivo del bundle, no sobre este reporte."
    ),
    "verify.ebs": (
        "Bundle EBS v1: `python3 forensics/verify_ebs_v1.py {name}` recalcula "
        "`bundle_hash` y `analysis_fingerprint` sobre el payload (todo menos "
        "`integrity`). Exit 0 significa que pasaron todos los chequeos; exit 1 lista "
        "los que fallaron."
    ),
    "verify.agent": (
        "Bundle de agente: `sha256sum -c {name}.sha256` compara el archivo contra el "
        "digest escrito a su lado al sellarlo. Si existe un hermano "
        "`_reasoning_trace.json`, `vigia.core.reasoning_trace.verify_reasoning_trace` "
        "ata su veredicto a `agent_verdict`."
    ),
    "verify.mcp": (
        "Bundle de investigación Modo 2: `python3 verify_tool_log.py {name}` recorre "
        "la cadena de hashes de `tool_execution_log` (v1 y v2, más el ancla "
        "`chain_tip_sha256` cuando está). Exit 0 cadena intacta, 1 cadena rota, 2 "
        "error de uso. Pasá `--hmac-key-file` para verificación con clave."
    ),
    "verify.family_note": (
        "Correr un verificador sobre la familia equivocada reporta no conformidad "
        "por diseño (docs/EXECUTION_MODES.md). Usá el comando que corresponde a la "
        "familia indicada en la cabecera."
    ),
    "verify.unknown": (
        "No se pudo identificar la familia, así que no aplica ningún verificador. "
        "Comparé el SHA-256 de la cabecera con tu propio `sha256sum` del archivo."
    ),
    "schema.ebs_v1": (
        "EBS v1: el bundle sellado del pipeline (`evidence_graph`, `decision_trace`, "
        "`integrity`). Lo produce `vigia/core/bundle_builder.py`."
    ),
    "schema.agent_audit": (
        "Bundle de auditoría del agente: salida de `python3 vigia_agent.py` (Modo 1). "
        "Lleva `agent_verdict`, `audit_trail`, `pipeline_results` y una `narrative` "
        "determinista. Los números son Fractions exactas."
    ),
    "schema.mcp_investigation": (
        "Bundle de investigación Modo 2: hallazgos y un `tool_execution_log` a "
        "prueba de manipulación, escritos durante una investigación en Claude Code / "
        "MCP. Los nombres de campo varían entre casos."
    ),
    "schema.unknown": (
        "Documento no reconocido: no coincidió con ninguna de las tres familias de "
        "bundle. No se infiere nada de él."
    ),
    "unknown.body": (
        "El archivo no coincidió con ninguna familia de bundle conocida, así que no "
        "hay veredicto que presentar. Sólo se informa el hash de origen de arriba. "
        "Abrí el JSON directamente o preguntale al perito qué herramienta lo produjo."
    ),

    # ------------------------------------------------------------ vista junior
    "junior.s1.title": "1. El veredicto",
    "junior.s1.intro": (
        "Este es el resultado sellado, copiado carácter por carácter del bundle. "
        "Cada línea indica el campo del que salió."
    ),
    "junior.s1.none": (
        "El bundle no tiene ningún campo con veredicto. Tratá el caso como no "
        "resuelto y revisá la sección de huecos."
    ),
    "junior.s1.disagreement": (
        "Dos campos con veredicto no coinciden. Este reporte no elige uno: el bundle "
        "selló ambos y un perito tiene que explicar la diferencia. No actúes sobre el "
        "más severo sólo porque es más severo."
    ),
    "junior.s1.hypothesis_note": (
        "`best_hypothesis` es la etiqueta de la hipótesis abductiva ganadora, no un "
        "veredicto. El veredicto es `agent_verdict`."
    ),
    "junior.s2.title": "2. Qué significa este veredicto",
    "junior.s2.scale_intro": (
        "VIGÍA usa una escala de cinco peldaños. El peldaño dice cuánta conducta "
        "deliberada sostiene la evidencia; no dice quién lo hizo ni si se violó una "
        "ley."
    ),
    "junior.s2.col_verdict": "Veredicto",
    "junior.s2.col_meaning": "Significado",
    "junior.s2.col_bar": "Vara de evidencia",
    "junior.s2.this_one": "Este bundle",
    "junior.s2.mode1_note": (
        "El Modo 1 (`vigia_agent.py`) no tiene peldaño INTENT: los casos límite que "
        "calificarían como INTENT quedan tapados en SUSPICION por el pipeline de "
        "scoring (CLAUDE.md, Verdict Scale). Un bundle de agente que dice SUSPICION "
        "puede ser más fuerte de lo que parece; leé la narrativa."
    ),
    "scale.NOISE.meaning": (
        "Todo lo observado se explica por mala configuración, error de software u "
        "operación normal."
    ),
    "scale.NOISE.bar": "Basta una sola fuente.",
    "scale.SUSPICION.meaning": (
        "Hay una anomalía estructural, pero no hay evidencia de ocultamiento "
        "deliberado ni de coordinación."
    ),
    "scale.SUSPICION.bar": "Una fuente más una desviación documentada respecto del baseline.",
    "scale.INTENT.meaning": (
        "Se tomaron decisiones deliberadas para producir este resultado."
    ),
    "scale.INTENT.bar": "Dos fuentes independientes y un protocolo de refutación superado.",
    "scale.MALICE.meaning": (
        "Ocultamiento activo de la intención: el actor esconde que está escondiendo "
        "(borrado de logs, manipulación de timestamps, enmascaramiento, falsas "
        "banderas)."
    ),
    "scale.MALICE.bar": (
        "Dos fuentes independientes, protocolo de refutación y un `devil_advocate` "
        "completo."
    ),
    "scale.ABSTAIN.meaning": (
        "No hay evidencia suficiente para clasificar. El hueco queda documentado "
        "como limitación."
    ),
    "scale.ABSTAIN.bar": "Declaración explícita de lo que falta.",
    "scale.ERROR.meaning": (
        "La corrida no terminó. Es una etiqueta de exit code, no un hallazgo forense."
    ),
    "scale.ERROR.bar": "No aplica.",
    "junior.s3.title": "3. Qué hacer ahora",
    "junior.s3.intro": (
        "Pasos SOC genéricos para este peldaño. No son consejo específico del caso y "
        "no salen del bundle; adaptalos a tu runbook."
    ),
    "next.NOISE": (
        "- Cerrá o bajá la prioridad de la alerta, guardando el bundle con el "
        "ticket.\n"
        "- Anotá qué comportamiento normal explicó la anomalía, para que el próximo "
        "analista no la reabra.\n"
        "- Si el sistema de origen es crítico, agendá una revisión de rutina en vez "
        "de un incidente."
    ),
    "next.SUSPICION": (
        "- Mantené el caso abierto. Todavía no contengas ni bloquees.\n"
        "- Buscá una segunda fuente independiente de la misma anomalía (otro host, "
        "otro log, otro sensor).\n"
        "- Pedile a un analista con experiencia que revise antes de escalar."
    ),
    "next.INTENT": (
        "- Escalá a respuesta a incidentes. La conducta deliberada está "
        "establecida.\n"
        "- Preservá la evidencia original en sólo lectura; trabajá sobre copias.\n"
        "- Empezá a dimensionar: ¿qué otros sistemas pudo tocar el mismo actor?"
    ),
    "next.MALICE": (
        "- Escalá ahora. Ocultamiento significa que el actor espera que lo "
        "busquen.\n"
        "- Preservá todo, incluidos los logs que el actor pudo intentar borrar.\n"
        "- Las decisiones de contención son de respuesta a incidentes y de la "
        "dirección, no de este reporte."
    ),
    "next.ABSTAIN": (
        "- No lo trates como benigno. Significa indeciso.\n"
        "- Leé la sección de huecos: lista qué evidencia resolvería el caso.\n"
        "- Recolectá esa evidencia, volvé a correr el análisis y comparé los dos "
        "bundles."
    ),
    "next.ERROR": (
        "- El análisis no terminó. Arreglá la corrida antes de razonar sobre el "
        "caso.\n"
        "- Revisá el audit trail o el log para ubicar el paso que falló."
    ),
    "next.UNKNOWN": (
        "- El token de veredicto no está en la escala estándar. Preguntale al perito "
        "qué lo produjo antes de actuar."
    ),
    "junior.s4.title": "4. Qué NO concluir",
    "notnot.NOISE": (
        "NOISE no es prueba de inocencia. Significa que los artefactos analizados se "
        "explican sin intención; los artefactos que nunca se recolectaron no están "
        "cubiertos."
    ),
    "notnot.SUSPICION": (
        "SUSPICION no es atribución. Nada acá dice quién lo hizo, y la anomalía "
        "todavía puede tener una causa inocente que no se probó."
    ),
    "notnot.INTENT": (
        "INTENT no es culpabilidad. Es una inferencia sobre conducta deliberada en "
        "los artefactos analizados, alcanzada mediante un protocolo de refutación, "
        "no un hallazgo legal."
    ),
    "notnot.MALICE": (
        "MALICE describe un patrón de ocultamiento en los artefactos analizados. No "
        "es un hallazgo legal, no identifica a una persona y no afirma nada sobre "
        "el daño."
    ),
    "notnot.ABSTAIN": (
        "ABSTAIN no es benigno ni malicioso. Es el sistema negándose a adivinar."
    ),
    "notnot.ERROR": "Una corrida en ERROR no dice nada sobre la evidencia.",
    "notnot.generic": (
        "Ninguna presentación, esta incluida, puede agregar evidencia que el bundle "
        "no contiene."
    ),
    "junior.s5.title": "5. Hallazgos, en lenguaje llano",
    "junior.s5.intro_mcp": (
        "Cada hallazgo de abajo fue registrado por el investigador durante una "
        "sesión de Modo 2. Su veredicto, confianza y estado se citan tal cual, "
        "seguidos de las tres capas peirceanas con las que se razonó."
    ),
    "junior.s5.intro_agent": (
        "Los bundles de agente no llevan veredicto por hallazgo. Registran señales "
        "(una por artefacto analizado) y una hipótesis abductiva. La narrativa "
        "sellada de abajo es el relato del propio pipeline."
    ),
    "junior.s5.intro_ebs": (
        "Los bundles EBS v1 registran una traza de decisión y, cuando corrió el "
        "módulo CAIE, una cadena de razón. Ambas se citan tal cual."
    ),
    "junior.s5.no_findings": "Este bundle no registra hallazgos ni señales.",
    "junior.s5.no_signal_verdict": (
        "Las señales no tienen veredicto propio; sólo el caso lo tiene."
    ),
    "junior.s5.peirce_first": (
        "Firstness: qué se observó, descripto sin interpretar."
    ),
    "junior.s5.peirce_second": (
        "Secondness: cómo la observación choca con lo que se ve normalmente."
    ),
    "junior.s5.peirce_third": (
        "Thirdness: qué patrón repetible y deliberado la produciría."
    ),
    "junior.s5.narrative_label": "Narrativa sellada (tal cual)",
    "junior.s5.gates_title": "Correcciones registradas antes de sellar el veredicto",
    "junior.s5.gates_intro": (
        "Un veredicto candidato que un gate rechazó nunca llegó a ser el veredicto. "
        "Es el sistema corrigiéndose antes de emitir, no una contradicción."
    ),
    "junior.s5.summary_label": "Resumen ejecutivo del investigador (tal cual)",
    "signals.col_artifact": "Artefacto",
    "signals.col_type": "Tipo de evidencia",
    "signals.col_source": "Herramienta de origen",
    "signals.col_confidence": "Confianza",
    "signals.col_z": "z-score",
    "signals.exact_note": (
        "Confianza y z-score son fracciones exactas, mostradas como "
        "numerador/denominador. No son porcentajes."
    ),
    "finding.verdict": "Veredicto",
    "finding.confidence": "Confianza",
    "finding.status": "Estado",
    "finding.artifacts": "Artefactos",
    "finding.tools": "Herramientas usadas",
    "finding.carnegie": "Patrón de persuasión (Carnegie)",
    "finding.devil_advocate": "Explicación benigna más fuerte (`devil_advocate`)",
    "finding.corroboration": "Corroboración",
    "finding.untitled": "(hallazgo sin título)",
    "junior.s6.title": "6. Técnicas MITRE ATT&CK mencionadas",
    "junior.s6.intro": (
        "Ids de técnica encontrados en el bundle, con el nombre y la descripción de "
        "MITRE cuando el diccionario local de VIGÍA los tiene. Las descripciones son "
        "el texto en inglés de MITRE y no se traducen."
    ),
    "junior.s6.none": "Este bundle no registra ningún id de técnica MITRE.",
    "mitre.col_id": "Técnica",
    "mitre.col_name": "Nombre",
    "mitre.col_where": "Encontrada en",
    "mitre.not_local": (
        "no está en el diccionario local de VIGÍA; URL derivada del id"
    ),
    "junior.s7.title": "7. Dónde cae esto en el ciclo de incidentes SANS",
    "junior.s7.intro": (
        "Un veredicto sellado es una salida de la fase de Identificación. La "
        "contención, la erradicación y la recuperación son decisiones humanas que "
        "este reporte no toma."
    ),
    "junior.s7.phase_in_bundle": "Fase registrada en el bundle (`sans_phase`)",
    "junior.s7.sans_compliance_note": (
        "`sans_compliance` en un bundle de agente lista criterios de la entrega del "
        "hackathon (audit trail presente, autocorrección ejecutada, etcétera). No es "
        "una fase PICERL."
    ),
    "picerl.col_phase": "Fase",
    "picerl.col_desc": "Qué pasa acá",
    "picerl.preparation": "Construir y mantener la capacidad de respuesta: política, herramientas, entrenamiento.",
    "picerl.identification": (
        "Detectar, alertar y decidir si el evento es un incidente. Recolección "
        "inicial de evidencia y triage. El veredicto de VIGÍA vive acá."
    ),
    "picerl.containment": (
        "Limitar el daño: aislar sistemas comprometidos preservando la evidencia."
    ),
    "picerl.eradication": "Eliminar el artefacto malicioso y su causa raíz.",
    "picerl.recovery": "Restaurar la operación normal y monitorear de cerca.",
    "picerl.lessons_learned": (
        "Documentar el incidente, mejorar detecciones y playbooks."
    ),
    "junior.s8.intro": (
        "Todo lo que el bundle no dice se lista acá en vez de completarse. Que falte "
        "no significa que no exista en la realidad; significa que no quedó "
        "registrado."
    ),
    "junior.s8.none": "El lector de bundles no reportó huecos.",
    "junior.s8.bundle_limitations": "Limitaciones que el propio bundle declara",
    "junior.s8.reader_gaps": "Campos que el lector de bundles no encontró",

    # ------------------------------------------------------------ vista experta
    "expert.s1.title": "1. Cadena de custodia",
    "expert.s1.intro": (
        "Cada ancla de custodia que define esta familia, presente o explícitamente "
        "ausente. Los valores son los literales sellados."
    ),
    "expert.s1.sidecar_note": (
        "Los bundles de agente no embeben su propio digest (autorreferencia). El "
        "digest del archivo vive en el sidecar `.sha256` y en `audit_trail`."
    ),
    "custody.col_field": "Campo",
    "custody.col_value": "Valor sellado",
    "expert.s2.title": "2. Campos con veredicto",
    "expert.s2.col_source": "Campo",
    "expert.s2.col_verdict": "Valor",
    "expert.s2.col_confidence": "Confianza",
    "expert.s2.col_pointer": "JSON pointer",
    "expert.s2.disagreement": (
        "`verdict_disagreement` está activo: los campos de arriba no coinciden. El "
        "bundle selló ambos; nada acá los reconcilia (ver "
        "docs/VIGIA_TECHNICAL_STATE_EN.md, sección 12.3)."
    ),
    "expert.s2.none": "No se encontró ningún campo con veredicto.",
    "expert.s3.title": "3. Tríada peirceana por hallazgo (tal cual)",
    "expert.s3.none_agent": (
        "Los bundles de agente no llevan tríada por señal. La narrativa abductiva es "
        "el único texto peirceano sellado en esta familia."
    ),
    "expert.s3.none": "Este bundle no registra ninguna tríada peirceana.",
    "expert.s3.layer_first": "Firstness",
    "expert.s3.layer_second": "Secondness",
    "expert.s3.layer_third": "Thirdness",
    "expert.s4.title": "4. Scores sellados exactos",
    "expert.s4.intro": (
        "Cada valor es el literal sellado en el bundle: Fractions serializadas como "
        "`numerador/denominador`, floats como su literal JSON. Nada se redondea ni se "
        "convierte. Un float en un camino sellado es en sí mismo un hallazgo "
        "(KNOWN_LIMITATIONS L-021, L-073)."
    ),
    "expert.s4.col_pointer": "JSON pointer",
    "expert.s4.col_value": "Literal sellado",
    "expert.s4.none": "Este bundle no sella ningún score numérico.",
    "expert.s5.title": "5. Gates Daubert, refutación y abogado del diablo",
    "expert.s5.intro": (
        "Registros de un gate, un downgrade o una autocorrección, tal como quedaron "
        "guardados. Son las correcciones previas a la emisión que hacen defendible "
        "un veredicto."
    ),
    "expert.s5.gates_none": "No hay ningún registro de gate ni de autocorrección.",
    "expert.s5.da_title": "Entradas `devil_advocate`",
    "expert.s5.da_none": "No hay ningún campo `devil_advocate`.",
    "expert.s5.da_missing_for_intent": (
        "HUECO: hay un veredicto {verdict} sellado pero no hay `devil_advocate`. El "
        "Protocolo de Refutación (CLAUDE.md, Paso 3) lo exige para INTENT y MALICE. "
        "Este reporte no altera el veredicto; registra el hueco (KNOWN_LIMITATIONS "
        "L-022)."
    ),
    "expert.s5.col_pointer": "JSON pointer",
    "expert.s5.col_value": "Valor sellado",
    "expert.s6.title": "6. Registro de ejecución",
    "expert.s6.kind": "Tipo de registro",
    "expert.s6.entries": "Entradas",
    "expert.s6.chain_version": "`chain_version`",
    "expert.s6.chain_tip": "`chain_tip_sha256`",
    "expert.s6.chain_tip_hmac": "`chain_tip_hmac`",
    "expert.s6.present": "presente",
    "expert.s6.absent": "ausente",
    "expert.s6.sha256_entries": "Entradas con `entry_sha256`",
    "expert.s6.start": "`start_time`",
    "expert.s6.end": "`end_time`",
    "expert.s6.histogram": "Histograma (ordenado por cantidad, luego por nombre)",
    "expert.s6.listing": "Primeras {cap} entradas",
    "expert.s6.truncated": (
        "Listado truncado en {cap} de {total} entradas. Abrí el bundle para el resto."
    ),
    "expert.s6.system_state": "Campos de `system_state`",
    "expert.s6.none": "Este bundle no lleva registro de ejecución.",
    "expert.s6.col_label": "Etiqueta",
    "expert.s6.col_count": "Cantidad",
    "expert.s8.title": "8. Limitaciones conocidas",
    "expert.s8.intro": (
        "Limitaciones declaradas por el bundle, huecos encontrados por el lector, y "
        "las limitaciones del repositorio que acotan cualquier presentación de esta "
        "familia."
    ),
    "expert.s8.pointers": (
        "- L-004: la narrativa y el contenido de prompts son input redactado por el "
        "perito, no evidencia.\n"
        "- L-020: los bundles de Modo 2 no llevan `audit_trail` granular.\n"
        "- L-022: la validación de `devil_advocate` es en parte arquitectónica.\n"
        "- L-030 / L-031: los caminos de sellado difieren; los hashes no son "
        "comparables entre familias y `verify_ebs_v1.py` rechaza bundles no-EBS por "
        "diseño.\n"
        "- L-056: las arquitecturas de alerta de Modo 1 y Modo 2 divergen.\n"
        "- L-074: esta presentación muestra los campos sellados tal cual y no puede "
        "llenar huecos que una familia no registra."
    ),
}

STRINGS: dict[str, dict[str, str]] = {"en": _EN, "es": _ES}


def t(lang: str, key: str, **fmt: Any) -> str:
    """Localized string for ``key``. Raises ``KeyError`` when the key or the
    language is unknown: no silent fallback, ever."""
    table = STRINGS[lang]
    text = table[key]
    return text.format(**fmt) if fmt else text


__all__ = ["STRINGS", "t"]
