# vigia/core/reasoning/abduction.py — ABDUCTIVE TRIBUNAL
#
# No Constitution. Only reasoning. Generates hypotheses, never judges.
# Deterministic. No floats. No probabilities. No ML.
#
# ---------------------------------------------------------------------------
# ATTRIBUTION
# ---------------------------------------------------------------------------
# Architecture and original implementation:
#     Kimi (Moonshot AI) — VIGIA AI Collective.
#     Kimi's central correction was removing a single "EpistemicStatus" that
#     silently mixed two dimensions, and splitting it into HypothesisMode
#     (what kind of explanation this is) and EvaluationState (where it sits in
#     the engine's lifecycle). AbductivePattern was introduced as a layer
#     between raw observation and generated hypothesis so that rules recognize
#     patterns instead of degenerating into stimulus-response reflexes.
#
#     The constraint the whole file exists to enforce:
#         An observation does not destroy a claim. It modifies the abductive
#         space.
#     That is the Peircean reading: a sign does not kill its object nor
#     replace the theory; it generates a possible inference which must then
#     enter a process of evaluation.
#
# Design review of the previous revision:
#     ChatGPT (OpenAI) — VIGIA AI Collective.
#     Graded the prior revision 8.5/10 and located the residual gaps: free
#     text still sitting where types belong, and Hypothesis.statement carrying
#     the causal content as prose rather than structure.
#
# Integration, defect repair and determinism hardening:
#     Claude (Anthropic). See docs/EPISTEMIC_KERNEL.md.
#
# Separations that must survive any refactor of this file:
#     authority != evidence
#     observation != interpretation
#     interpretation != hypothesis
#     hypothesis != verdict
#     operational state != epistemic force
#     origin of a claim != justification of a claim
# Fewer classes is not a better design here. The test of understanding is
# being able to say which error becomes unrepresentable if a class is removed.
# ---------------------------------------------------------------------------

from dataclasses import dataclass, field
from typing import Optional, Set, Tuple, Dict, List, FrozenSet
from enum import Enum, auto
from datetime import datetime

# Imports from Constitution (ontology.py)
from ..ontology import (
    Domain,
    AuthorityLayer,
    ClaimRole,
    OriginKind,
    JustificationMode,
    SourceType,
    ObservationKind,
    TemporalCoverage,
    ClaimStatus,
    RevisionPolicy,
    AuthoritySource,
    ObservationPayload,
    ClaimContext,
    OntologyClaim,
    Observation,
    OntologyRegistry,
    KernelSnapshot,
)


# =============================================================================
# PART I: SEMIOTIC TAXONOMY (Peirce — separated from computational types)
# =============================================================================

class SignRelation(Enum):
    """Peircean semiotics. Describes how a sign relates to its object."""
    INDEX = auto()
    ICON = auto()
    SYMBOL = auto()


class NodeType(Enum):
    """Computational node types. Semantics lives in SignRelation, not here."""
    CLAIM = auto()
    OBSERVATION = auto()
    HYPOTHESIS = auto()
    CONTEXT = auto()


class HypothesisMode(Enum):
    """What kind of explanation the hypothesis provides. Not probability."""
    CAUSAL = auto()
    CONTEXTUAL = auto()
    EXPLANATORY = auto()
    ALTERNATIVE = auto()


class EvaluationState(Enum):
    """Lifecycle state of a hypothesis in the engine. Not epistemic force."""
    GENERATED = auto()
    CONSISTENT = auto()
    INCOMPLETE = auto()
    DISCARDED = auto()


class InferenceKind(Enum):
    """Generated by the engine. Not part of the ontology."""
    ABDUCTIVE = auto()
    DEDUCTIVE = auto()
    INDUCTIVE = auto()


class AbductiveVerdict(Enum):
    """
    The Tribunal never outputs CONFLICT_DETECTED as primary verdict.
    It generates hypotheses. Conflict emerges from hypothesis evaluation.
    """
    COMPATIBLE = auto()
    GENERATES_HYPOTHESIS = auto()
    REQUIRES_CONTEXT = auto()
    ABSTAIN = auto()


class ConflictRelation(Enum):
    """Fine-grained conflict types. Used in secondary evaluation, not primary output."""
    REFUTATION = auto()
    EXCEPTION = auto()
    INAPPLICABLE = auto()
    DEGRADATION = auto()
    VERSION_MISMATCH = auto()
    AMBIGUOUS = auto()


# =============================================================================
# PART II: CLAIM GRAPH (Intermediate semantic layer — computational nodes)
# =============================================================================

@dataclass(frozen=True)
class ClaimNode:
    """
    Computational node in the abductive graph.
    Semiotic relation (Peirce) is separate from node type.
    """
    node_id: str
    node_type: NodeType
    sign_relation: Optional[SignRelation] = None
    context: ClaimContext = field(default_factory=ClaimContext)
    status_at_evaluation: ClaimStatus = ClaimStatus.ACTIVE
    temporal_coverage: TemporalCoverage = TemporalCoverage.UNKNOWN


class ClaimGraph:
    """
    Directed graph of claim dependencies and semantic relationships.
    Not the abductive complex yet. The scaffold for it.

    Edge direction: `add_dependency(from_id, to_id)` means "from_id depends on
    to_id". Therefore `dependencies(from_id)` contains to_id, and
    `dependents(to_id)` contains from_id — the same direction the registry's
    reverse graph uses. The two accessors were transposed relative to that
    reading before integration, so a caller asking for dependents received
    dependencies and the cascade would have walked the graph backwards.
    """

    def __init__(self):
        self._nodes: Dict[str, ClaimNode] = {}
        self._edges: Dict[str, Set[str]] = {}     # node -> what it depends on
        self._reverse: Dict[str, Set[str]] = {}   # node -> what depends on it

    def add_node(self, node: ClaimNode) -> None:
        self._nodes[node.node_id] = node
        self._edges.setdefault(node.node_id, set())
        self._reverse.setdefault(node.node_id, set())

    def add_dependency(self, from_id: str, to_id: str) -> None:
        """Record that `from_id` depends on `to_id`."""
        self._edges.setdefault(from_id, set()).add(to_id)
        self._reverse.setdefault(to_id, set()).add(from_id)

    def node(self, node_id: str) -> Optional[ClaimNode]:
        return self._nodes.get(node_id)

    def node_ids(self) -> Tuple[str, ...]:
        return tuple(sorted(self._nodes))

    def dependencies(self, node_id: str) -> Tuple[str, ...]:
        """What this node depends on. Sorted — iteration order is contractual."""
        return tuple(sorted(self._edges.get(node_id, set())))

    def dependents(self, node_id: str) -> Tuple[str, ...]:
        """What depends on this node. Sorted — iteration order is contractual."""
        return tuple(sorted(self._reverse.get(node_id, set())))

    def subgraph(self, root_ids: FrozenSet[str]) -> "ClaimGraph":
        """
        Deterministic extraction of the transitive closure of what the roots
        depend on — the self-contained fragment needed to evaluate them.
        """
        visited: Set[str] = set()
        queue: List[str] = sorted(root_ids)
        while queue:
            nid = queue.pop(0)
            if nid in visited:
                continue
            visited.add(nid)
            for dep in self.dependencies(nid):
                if dep not in visited:
                    queue.append(dep)
        sub = ClaimGraph()
        for nid in sorted(visited):
            if nid in self._nodes:
                sub.add_node(self._nodes[nid])
        for nid in sorted(visited):
            for dep in self.dependencies(nid):
                if dep in visited:
                    sub.add_dependency(nid, dep)
        return sub


# =============================================================================
# PART III: ABDUCTIVE PATTERN (Layer between Observation and Hypothesis)
# =============================================================================

@dataclass(frozen=True)
class AbductivePattern:
    """
    Intermediate layer between raw observation and generated hypothesis.
    The Tribunal recognizes patterns, not just fires rules.

    Field order note: `causal_template` is required and therefore precedes the
    defaulted fields. In the pre-integration revision it followed two
    defaulted fields, which is a TypeError at class-definition time — the
    module could not be imported at all. See docs/EPISTEMIC_KERNEL.md (D-2).
    """
    pattern_id: str
    observation_kind: ObservationKind
    causal_template: str
    affected_domain: Optional[Domain] = None
    affected_role: Optional[ClaimRole] = None
    required_context_keys: Tuple[str, ...] = field(default_factory=tuple)
    hypothesis_mode: HypothesisMode = HypothesisMode.EXPLANATORY


# =============================================================================
# PART IV: HYPOTHESIS (The primary output of the Tribunal)
# =============================================================================

@dataclass(frozen=True)
class Hypothesis:
    """
    Output of the Tribunal. Not a verdict. An abductive candidate.
    Epistemic status separated into mode (what kind) and state (where in
    lifecycle).

    `required_context_keys` carries the names of the context a rule declared
    necessary. The pre-integration revision built this as a tuple of empty
    ClaimContext objects, one per declared key — preserving the count and
    discarding every name, so a hypothesis could report "I need two things"
    without being able to say which two. The keys are the audit-relevant part.

    `statement` remains prose. The ChatGPT review is right that an auditable
    machine will eventually need a causal structure (cause / condition /
    effect nodes) with the prose derived from it rather than primary. That is
    a design decision for the maintainer, not a repair to make in passing; it
    is recorded as an open question in docs/EPISTEMIC_KERNEL.md.
    """
    hypo_id: str
    statement: str
    hypothesis_mode: HypothesisMode
    evaluation_state: EvaluationState
    supporting_observations: Tuple[str, ...]
    supporting_claims: Tuple[str, ...]
    required_context_keys: Tuple[str, ...] = field(default_factory=tuple)
    generated_by_pattern: Optional[str] = None


# =============================================================================
# PART V: ABDUCTIVE TRIBUNAL (Generates hypotheses. Never judges.)
# =============================================================================

@dataclass(frozen=True)
class TribunalRule:
    """
    A rule in the Tribunal.
    Maps observations to abductive effects on claims.
    Primary output is always hypothesis generation or compatibility assessment.
    """
    # Target filters (None = wildcard)
    target_domain: Optional[Domain] = None
    target_layer: Optional[AuthorityLayer] = None
    target_role: Optional[ClaimRole] = None

    # Observation trigger
    obs_kind: Optional[ObservationKind] = None
    obs_domain: Optional[Domain] = None

    # Abductive effect
    verdict: AbductiveVerdict = AbductiveVerdict.ABSTAIN
    generates_hypothesis: Optional[str] = None
    required_context: Tuple[str, ...] = field(default_factory=tuple)
    hypothesis_mode: HypothesisMode = HypothesisMode.EXPLANATORY


class AbductiveTribunal:
    """
    The Tribunal. Does not contradict claims directly.
    Observations modify the abductive space. Claims are questioned, not refuted.
    """

    def __init__(self):
        self._rules: List[TribunalRule] = []
        self._patterns: List[AbductivePattern] = []

    def add_rule(self, rule: TribunalRule) -> None:
        self._rules.append(rule)

    def add_pattern(self, pattern: AbductivePattern) -> None:
        self._patterns.append(pattern)

    def _match_rules(
        self,
        observation: Observation,
        claim: OntologyClaim
    ) -> List[TribunalRule]:
        """Collect all matching rules. Deterministic (registration order)."""
        matches: List[TribunalRule] = []
        for rule in self._rules:
            if rule.target_domain is not None and claim.domain != rule.target_domain:
                continue
            if rule.target_layer is not None and claim.layer != rule.target_layer:
                continue
            if rule.target_role is not None and claim.claim_role != rule.target_role:
                continue
            if rule.obs_kind is not None and observation.kind != rule.obs_kind:
                continue
            if rule.obs_domain is not None and observation.domain != rule.obs_domain:
                continue
            matches.append(rule)
        return matches

    def _generate_hypothesis(
        self,
        rule: TribunalRule,
        observation: Observation,
        claim: OntologyClaim
    ) -> Optional[Hypothesis]:
        """Generate a hypothesis from a matched rule. Never judge."""
        if rule.verdict != AbductiveVerdict.GENERATES_HYPOTHESIS:
            return None
        if not rule.generates_hypothesis:
            return None
        return Hypothesis(
            hypo_id=f"hypo.{observation.obs_id}.{claim.claim_id}",
            statement=rule.generates_hypothesis,
            hypothesis_mode=rule.hypothesis_mode,
            evaluation_state=EvaluationState.GENERATED,
            supporting_observations=(observation.obs_id,),
            supporting_claims=(claim.claim_id,),
            required_context_keys=tuple(rule.required_context),
            generated_by_pattern=None,
        )

    def evaluate(
        self,
        observation: Observation,
        claim: OntologyClaim
    ) -> Tuple[AbductiveVerdict, Optional[Hypothesis]]:
        """
        Deterministic. Collects ALL matching rules.
        If all agree: returns that verdict.
        If they disagree: returns ABSTAIN.
        If none match: returns ABSTAIN.
        Primary output is always GENERATES_HYPOTHESIS or COMPATIBLE.
        Never CONFLICT_DETECTED as primary.

        Agreement is checked on the verdict AND on the hypothesis the rules
        would generate. Two rules that both say GENERATES_HYPOTHESIS but
        propose different explanations do not agree in any sense that matters:
        emitting only the first-registered one would silently discard a rival
        abduction, which is precisely the collapse this engine exists to
        prevent. Disagreement at that level abstains, same as verdict-level
        disagreement.
        """
        matches = self._match_rules(observation, claim)

        if not matches:
            return (AbductiveVerdict.ABSTAIN, None)

        verdicts = set(r.verdict for r in matches)
        if len(verdicts) > 1:
            return (AbductiveVerdict.ABSTAIN, None)

        proposals = set(
            (r.generates_hypothesis, r.hypothesis_mode, tuple(r.required_context))
            for r in matches
        )
        if len(proposals) > 1:
            return (AbductiveVerdict.ABSTAIN, None)

        rule = matches[0]
        hypo = self._generate_hypothesis(rule, observation, claim)

        return (rule.verdict, hypo)

    def evaluate_all(
        self,
        observation: Observation,
        registry: OntologyRegistry
    ) -> Dict[str, Tuple[AbductiveVerdict, Optional[Hypothesis]]]:
        """
        Evaluate an observation against all active claims in a domain.

        Insertion order follows registry.by_domain(), which is sorted by
        claim_id, so the returned mapping serializes identically across runs.
        """
        results: Dict[str, Tuple[AbductiveVerdict, Optional[Hypothesis]]] = {}
        for claim in registry.by_domain(observation.domain):
            if registry.status(claim.claim_id) == ClaimStatus.ACTIVE:
                results[claim.claim_id] = self.evaluate(observation, claim)
        return results

    def match_patterns(
        self,
        observation: Observation
    ) -> List[AbductivePattern]:
        """Match observation against known abductive patterns. Deterministic."""
        matched: List[AbductivePattern] = []
        for pattern in self._patterns:
            if observation.kind != pattern.observation_kind:
                continue
            if (pattern.affected_domain is not None
                    and observation.domain != pattern.affected_domain):
                continue
            # Check required context keys exist in observation
            obs_ctx = observation.context_dict()
            if all(k in obs_ctx for k in pattern.required_context_keys):
                matched.append(pattern)
        return matched


# =============================================================================
# PART VI: ASSESSMENT MATRIX (Structured epistemic report, not a verdict)
# =============================================================================

@dataclass(frozen=True)
class AssessmentCell:
    """One cell in the assessment matrix. One claim, one observation, one relation."""
    layer: AuthorityLayer
    claim_id: str
    observation_id: str
    verdict: AbductiveVerdict
    hypothesis: Optional[Hypothesis]
    status: ClaimStatus
    temporal_coverage: TemporalCoverage


@dataclass(frozen=True)
class AssessmentMatrix:
    """
    The Tribunal does not emit PASS/FAIL.
    It emits a matrix of abductive assessments per claim/observation pair.
    """
    cells: Tuple[AssessmentCell, ...]
    evaluated_at: datetime
    kernel_snapshot: Optional[KernelSnapshot] = None

    def by_layer(self, layer: AuthorityLayer) -> Tuple[AssessmentCell, ...]:
        return tuple(c for c in self.cells if c.layer == layer)

    def by_claim(self, claim_id: str) -> Tuple[AssessmentCell, ...]:
        return tuple(c for c in self.cells if c.claim_id == claim_id)

    def hypotheses(self) -> Tuple[Hypothesis, ...]:
        seen: Set[str] = set()
        hypos: List[Hypothesis] = []
        for c in self.cells:
            if c.hypothesis and c.hypothesis.hypo_id not in seen:
                seen.add(c.hypothesis.hypo_id)
                hypos.append(c.hypothesis)
        return tuple(hypos)


# =============================================================================
# PART VII: EPISTEMIC REPORT (The final output of VIGÍA)
# =============================================================================

@dataclass(frozen=True)
class EpistemicReport:
    """
    The final output of VIGÍA is not a verdict.
    It is a structured epistemic report with full traceability.

    `evaluated_at` is required and injected by the caller. It carried a
    `default_factory=datetime.utcnow` before integration, which reads the
    wall clock at construction time: two runs over identical evidence would
    produce two different reports, and no third party could reproduce either.
    Removing implicit clock reads from the ontology was one of the deliberate
    choices of this revision; the report layer had kept one.
    """
    report_id: str
    engine_version: str
    ruleset_version: str
    kernel_snapshot: KernelSnapshot
    assessment_matrix: AssessmentMatrix
    matched_patterns: Tuple[AbductivePattern, ...]
    evaluated_at: datetime
    abstention_reason: Optional[str] = None
    causal_coherence_note: str = ""
